version: '3'
services:
  code-review-bot:
    build:
      context: ./
      dockerfile: Dockerfile-local
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/src
    ports:
      - 3000:3000
