name: Publish on new release

on:
  release: 
    types: [published]

jobs:
  publish:
    name: Publish Release Tag on Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish to Registry
        uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          tag: ${{ steps.package-version.outputs.current-version }}
          registry: docker.io
          image: ${{ secrets.DOCKERHUB_REPOSITORY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
