name: Validate PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-test:
    name: Validate PR on ${{ matrix.os }}@${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['10', '12', '14', '16']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: npm run lint
        run: npm run lint
      - name: npm run test
        run: npm run test
      - name: npm run build
        run: npm run build
